version: "3.4"

services:
  frontend:
    build:
      target: base
    volumes:
      - ./frontend/src:/base/src
      - ./frontend/public:/base/public
      - ./frontend/tailwind.config.js:/base/tailwind.config.js
    command: yarn dev
    ports:
      - "3000:3000"
  strapi:
    ports:
      - "1337:1337"
