version: "3.4"

services:
  frontend:
    build:
      target: base
    volumes:
      - ./frontend/src:/base/src
      - ./frontend/public:/base/public
      - ./frontend/tailwind.config.js:/base/tailwind.config.js
    command: yarn dev
    ports:
      - "3000:3000"
  strapi:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.boilerplate_strapi.rule=Host(`strapi.mediaatrium.de`)"
      - "traefik.http.routers.boilerplate_strapi.entrypoints=https"
      - "traefik.http.routers.boilerplate_strapi.tls.certresolver=httpresolver"
      - "traefik.docker.network=traefik_network"
    networks:
      - traefik_network
      - default
